"""Shared facade method contracts for local and remote servers."""

from __future__ import annotations

from typing import Protocol

from serverkit.cron.manager import CronCollection
from serverkit.disk.manager import DiskCollection
from serverkit.docker.manager import ContainerCollection, DockerManager
from serverkit.env.vars import EnvSnapshot
from serverkit.logs.logfile import LogFile
from serverkit.memory.snapshot import MemorySnapshot
from serverkit.network.manager import NetworkManager
from serverkit.processes.history import ProcessHistory
from serverkit.processes.manager import ProcessCollection
from serverkit.ports.manager import PortCollection
from serverkit.remote.facade_managers import (
    RemoteDockerManager,
    RemoteNetworkManager,
    RemoteUsersManager,
)
from serverkit.remote.systemctl import RemoteSystemctlManager
from serverkit.services.manager import ServiceCollection
from serverkit.systemctl.manager import SystemctlManager
from serverkit.users.manager import UsersManager


class ServerFacade(Protocol):
    """Structural type for :class:`~serverkit.core.server.Server` and :class:`~serverkit.remote.server.RemoteServer`."""

    @property
    def process_history(self) -> type[ProcessHistory]:
        """Namespace for :meth:`ProcessHistory.diff` (compare two process snapshots)."""
        ...

    def processes(self) -> ProcessCollection: ...
    def logs(self, path: str) -> LogFile: ...
    def memory(self) -> MemorySnapshot: ...
    def disk(self) -> DiskCollection: ...
    def network(self) -> NetworkManager | RemoteNetworkManager: ...
    def ports(self) -> PortCollection: ...
    def systemctl(self) -> SystemctlManager | RemoteSystemctlManager: ...
    def services(self) -> ServiceCollection: ...
    def service(self, name: str): ...
    def cron(self) -> CronCollection: ...
    def users(self) -> UsersManager | RemoteUsersManager: ...
    def env(self) -> EnvSnapshot: ...
    def docker(self) -> DockerManager | RemoteDockerManager: ...
    def containers(self) -> ContainerCollection: ...
    def run(self, name: str, *, dry_run: bool = False, executor: str | None = None) -> dict: ...
    def ask(self, query: str) -> str: ...
